using System;
using System.Collections.Generic;
using System.Text;
using System.Runtime.InteropServices;

namespace ITC_KEYBOARD
{
    /// <summary>
    /// a class to manage multikeys
    /// </summary>
    class CMultiKeys
    {
        /// <summary>
        /// a Multikeystruct is similar to an USBKeyStruct except to that
        /// it does not have an USB code page and USB HID scancode
        /// </summary>
        [Serializable]
        [StructLayout(LayoutKind.Sequential)]
        public struct MultiKeyStruct
        {
            /// <summary>
            /// high byte flags for the key definition
            /// </summary>
            public byte bFlagHigh;
            /// <summary>
            /// mid byte flags for the key definition
            /// </summary>
            public byte bFlagMid;
            /// <summary>
            /// low byte flags for the key definition
            /// </summary>
            public byte bFlagLow;
            /// <summary>
            /// the value generated by the key entry, a VKEY or an index into another table
            /// </summary>
            public byte bIntScan;
        }
        /// <summary>
        /// gives a text dump reprensentation of the multikey
        /// </summary>
        /// <param name="_theBytes">the MultiKeyStruct to dump</param>
        /// <returns>a string with the meanings of the structure</returns>
        public string dumpMultiKey(MultiKeyStruct _theBytes)
        {
            string s = _theBytes.bFlagLow.ToString("X02");
            s += "," + _theBytes.bFlagMid.ToString("X02");
            s += "," + _theBytes.bFlagHigh.ToString("X02");
            s += "," + _theBytes.bIntScan.ToString("X02");

            //getName does not care about extended etc...
            s += " '" + ITC_KEYBOARD.CUSBPS2_vals.Cusbps2key.getName(_theBytes.bIntScan) + "'";
            s += " | ";
            return s;
        }
        /// <summary>
        /// gives a text dump reprensentation of the multikey
        /// </summary>
        /// <param name="iIdx">the index of the MultiKeyStruct to dump</param>
        /// <returns>a string with the meanings of the structure</returns>
        public string dumpMultiKey(int iIdx)
        {
            byte[] bs = _MultiKeyStructList[iIdx - 1];
            MultiKeyStruct[] rs = RawDeserialize2(bs);
            string s = "->";
            for (int i = 0; i < rs.Length; i++)
            {
                s += dumpMultiKey(rs[i]);
            }
            return s;
        }

        private MultiKeyStruct[] _MultiKeyStructs;

        private int _multiKeyCount = 0;
        private List<byte[]> _MultiKeyStructList;

        public CMultiKeys()
        {
            //read number of entries
            int iCount = this.getMultiKeyCount();
            if (iCount == 0)
                throw new ArgumentNullException("Sorry, no MultiKeys supported");
            //create new arrays
            _MultiKeyStructList=new List<byte[]>(iCount+1);
            this.readAll();
        }
        /// <summary>
        /// converts an array of MultiKeyStruct to a byte array for
        /// storing into registry
        /// </summary>
        /// <param name="structData">the array to convert</param>
        /// <returns>a byte array ready to save to registry</returns>
        public byte[] RawSerialize(MultiKeyStruct[] structData)
        {
            //size
            int structSize = Marshal.SizeOf(structData[0]);
            int iRawSize = structData.Length * structSize;
            byte[] rawDatas = new byte[iRawSize];
            for (int i = 0; i < structData.Length; i++)
            {
                rawDatas[(i * structSize) + 0] = structData[i].bFlagHigh;
                rawDatas[(i * structSize) + 1] = structData[i].bFlagMid;
                rawDatas[(i * structSize) + 2] = structData[i].bFlagLow;
                rawDatas[(i * structSize) + 3] = structData[i].bIntScan;
            }
            return rawDatas;
        }
        /// <summary>
        /// converts a byte arrray as read from registry
        /// to an array of MultiKeyStruct
        /// </summary>
        /// <param name="rawData">the bytes as read from registry</param>
        /// <returns>array of MultiKeyStruct</returns>
        private static MultiKeyStruct[] RawDeserialize2(byte[] rawData)
        {
            int structSize = 4;
            int iCount = rawData.Length / structSize; //we have 4 bytes per struct
            MultiKeyStruct[] _multiStruct = new MultiKeyStruct[iCount];
            for (int i = 0; i < iCount; i++)
            {
                _multiStruct[i].bFlagHigh = rawData[i * structSize + 0];
                _multiStruct[i].bFlagMid = rawData[i * structSize + 1];
                _multiStruct[i].bFlagLow = rawData[i * structSize + 2];
                _multiStruct[i].bIntScan = rawData[i * structSize + 3];
            }
            return _multiStruct;
        }
        /// <summary>
        /// get the number of defined MultiKeys as readable from registry
        /// </summary>
        /// <returns>the number of MultiKeys</returns>
        public int getMultiKeyCount()
        {
            if (this._multiKeyCount != 0)
                return this._multiKeyCount;
            string regKeyb = CUSBkeys.getRegLocation() + @"\MultiKeys";
            Microsoft.Win32.RegistryKey tempKey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(regKeyb, true);
            int i = 1;
            object o = null;
            do
            {
                try
                {
                    o = tempKey.GetValue("Multi" + i.ToString());
                }
                catch (Exception)
                {
                    o = null;
                    break;
                }
                if(o!=null)
                    i++;
            } while (o!=null);
            if (i != 0)
                return i - 1;
            else
                return 0;
        }

        private void readAll()
        {
            int iCount = this.getMultiKeyCount();
            if (iCount == 0)
                return;
            //read all MultiKeys entries
            _MultiKeyStructs = new MultiKeyStruct[iCount];

            string regKeyb = CUSBkeys.getRegLocation() + @"\MultiKeys";
            Microsoft.Win32.RegistryKey tempKey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(regKeyb, true);


            for (int i = 1; i <= iCount; i++)
            {
                byte[] bMultiKeys = (byte[])tempKey.GetValue("Multi" + i.ToString());
                _MultiKeyStructs = RawDeserialize2(bMultiKeys);
                _MultiKeyStructList.Add(bMultiKeys);
            }
            tempKey.Close();
            System.Diagnostics.Debug.WriteLine("MultiKeys readall finished");
        }

    }
}
